specs for user delete fixes
chef/knife-opc pull request #56
Opened 2020-08-04 11:59 UTC by antima-gupta

### Description

- Added specs for user delete fixes.

### Issues Resolved

#36 

### Check List

- [ ] New functionality includes tests
- [ ] All tests pass
- [x] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco>
- [ ] PR title is a worthy inclusion in the CHANGELOG

2020-08-06 08:21 UTC, antima-gupta commented
@tylercloke I tried to rebase my branch with the master but it seems `lib/chef/knife/opc_user_delete.rb` having merge conflicts. Attaching conflict file [opc_user_delete_conflict.txt](https://github.com/chef/knife-opc/files/5033421/opc_user_delete_conflict.txt). Could you please rebase [PR](https://github.com/chef/knife-opc/pull/36), so that I can rebase this?

2020-08-07 16:22 UTC, tas50 commented
@antima-gupta This needs to get rebased off master. I think that may fix the specs not actually running in Buildkite

2020-08-14 09:42 UTC, antima-gupta commented
@tas50 I have rebase the PR. Please have a look.

2020-08-19 11:32 UTC, antima-gupta commented
@tas50 I have rebase this, Could you please have a look and let me know if any changes required?

2020-09-28 17:14 UTC, lamont-granquist commented on lib/chef/knife/opc_user_delete.rb
> -      description: "If the user is a member of any org admin groups, attempt to remove from those groups. Ignored if --no-disassociate-user is set."
this should not be getting removed, and a bunch of other stuff in here is not part of the other PR which is being rebased.

2020-09-28 17:15 UTC, tas50 commented
@antima-gupta The @tylercloke's old PR here came before @marcparadise added a lot of new functionality to this plugin here: https://github.com/chef/knife-opc/commit/c9f00fc48c8927e24f6342021236e4633f0534f7. It looks like your rebase of this PR is removing all the new functionality, which we'll want to keep. This is going to need some significant rework.

2020-09-28 17:15 UTC, tas50 requested changes
See comment above

2020-10-01 10:15 UTC, antima-gupta commented
@tas50 I debugged the new functionality and found the code behavior is same. We have option `--remove-from-admin-groups` in user delete command so we don't need these changes.

2021-02-22 19:32 UTC, lamont-granquist commented
merged knife-opc into chef/chef so closing this out, if its still relevant it needs to be moved:

https://github.com/chef/chef/pull/10187

2021-02-22 19:32 UTC, closed without merging